### PR TITLE
Website fixes

### PR DESCRIPTION
**Pull request by fillods**

### CODE REVIEW

**Comment by barak** [comment]
I've cherry-picked the web site commit. Not taking the m4/AX_* stuff, because it's in autoconf-archive package, and will be automatically included in distribution tarballs generated by autotools.

**Comment by fillods** [comment]
Alright, thanks.

BTW, @barak can you please remove the rotten URL `vobcopy.org` that is mentioned in the About section of the GitHub [repo](https://github.com/barak/vobcopy)  by clicking the parameter icon (top right corner). **Only you can do it**.
Thanks in advance.

**Comment by barak** [comment]
thanks @fillods, done

**Comment by fillods** [comment]
All fine, thanks 👌

**Pull request closed without merging**
