### PR TITLE
Some bugfixes and small improvements to `updateProgress()'

### PR DESCRIPTION
**Pull request by rxxrc**

### CODE REVIEW

**Comment by barak** [comment]
Manually merged (via cherry-pick) onto new master branch, which used to be "tweaks". Please confirm I did it right!

**Comment by rxxrc** [comment]
Oops, I guess maybe I should have PR'd `tweaks` instead; sorry.
It seems like you've missed my final (force-pushed) commit 12d0e26 ? Possibly I'm just not looking in the right place -- I'm still pretty inexperienced with git{,hub}.

**Comment by barak** [comment]
Okay, is "master" in my repo correct now?

**Comment by rxxrc** [comment]
Yep, looks good, thanks.

**Pull request closed without merging**
